package pl.szczesniak.dominik.tripreimbursementcalculator.reimbursementrequests.domain;

import pl.szczesniak.dominik.tripreimbursementcalculator.reimbursementconfiguration.domain.ReimbursementConfigurationService;

public class ReimbursementRequestServiceConfiguration {

	public ReimbursementRequestService reimbursementRequestService(final ReimbursementConfigurationService reimbursementConfigurationService) {
		return new ReimbursementRequestService(reimbursementConfigurationService, new InMemoryReimbursementRequestsRepository());
	}

}
